# Goal  - To run the end to end DevSecOps pipeline for the application

name: DevSecOps
on:
    push:
            branches: [master]

        # Code Stage with Shift-left
jobs:
    # Code Stage with Shift-left
    code_quality:
        uses: ./.github/workflows/code-quality.yml
    secret-scanning:
    # Secret Scanning Stage
        uses: ./.github/workflows/secret-scanning.yml
    # Dependency Scanning Stage
    dependency-scanning:
        uses: ./.github/workflows/dependency-scan.yml
    # Docker Scanning Stage
    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit