# Goal  - To run the end to end DevSecOps pipeline for the application

name: DevSecOps
on:
    push:
            branches: [master]

        # Code Stage with Shift-left
jobs:
    code_quality:
        uses: ./.github/workflows/code-quality.yml
    
