# Goal To install multiple versions of Go and do linting for multiple versions
name: Go linter

on:
  workflow_dispatch:

jobs:
  code-format:
    runs-on : ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22, 1.21, 1.20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Run go formatter
        run: go fmt 
        working-directory: backend

      - name: Run go vet
        run: go vet 
        working-directory: backend